name: ${project.name}
version: ${project.version}
description: ${project.description}
load: STARTUP
main: ${project.groupId}.${project.artifactId}.${project.name}
commands:
   ping:
     description: Pings the server.